[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [executing] maintenance: installing charm software
  untrusted-postgresql-k8s/1 [executing] maintenance: installing charm software
  untrusted-postgresql-k8s/2 [executing] blocked: Insufficient permissions, try: `juju trust untrusted-postgresql-k8s --scope=cluster`
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [executing] unknown: 
  untrusted-postgresql-k8s/1 [executing] unknown: 
  untrusted-postgresql-k8s/2 [executing] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [executing] unknown: 
  untrusted-postgresql-k8s/1 [executing] unknown: 
  untrusted-postgresql-k8s/2 [executing] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] unknown: 
  untrusted-postgresql-k8s/1 [idle] unknown: 
  untrusted-postgresql-k8s/2 [executing] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] unknown: 
  untrusted-postgresql-k8s/1 [idle] unknown: 
  untrusted-postgresql-k8s/2 [executing] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] unknown: 
  untrusted-postgresql-k8s/1 [idle] unknown: 
  untrusted-postgresql-k8s/2 [executing] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] unknown: 
  untrusted-postgresql-k8s/1 [idle] unknown: 
  untrusted-postgresql-k8s/2 [executing] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] unknown: 
  untrusted-postgresql-k8s/1 [idle] unknown: 
  untrusted-postgresql-k8s/2 [executing] waiting: awaiting for primary endpoint to be ready
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] unknown: 
  untrusted-postgresql-k8s/1 [idle] unknown: 
  untrusted-postgresql-k8s/2 [executing] waiting: awaiting for primary endpoint to be ready
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] unknown: 
  untrusted-postgresql-k8s/1 [idle] unknown: 
  untrusted-postgresql-k8s/2 [executing] waiting: awaiting for primary endpoint to be ready
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] unknown: 
  untrusted-postgresql-k8s/1 [idle] unknown: 
  untrusted-postgresql-k8s/2 [executing] waiting: awaiting for primary endpoint to be ready
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] unknown: 
  untrusted-postgresql-k8s/1 [idle] unknown: 
  untrusted-postgresql-k8s/2 [executing] waiting: awaiting for primary endpoint to be ready
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] unknown: 
  untrusted-postgresql-k8s/1 [idle] unknown: 
  untrusted-postgresql-k8s/2 [executing] waiting: awaiting for primary endpoint to be ready
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] unknown: 
  untrusted-postgresql-k8s/1 [idle] unknown: 
  untrusted-postgresql-k8s/2 [executing] waiting: awaiting for primary endpoint to be ready
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] unknown: 
  untrusted-postgresql-k8s/1 [idle] unknown: 
  untrusted-postgresql-k8s/2 [idle] waiting: awaiting for primary endpoint to be ready
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [executing] unknown: 
  untrusted-postgresql-k8s/1 [executing] unknown: 
  untrusted-postgresql-k8s/2 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] waiting: awaiting for cluster to start
  untrusted-postgresql-k8s/1 [idle] waiting: awaiting for cluster to start
  untrusted-postgresql-k8s/2 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] waiting: awaiting for cluster to start
  untrusted-postgresql-k8s/1 [idle] waiting: awaiting for cluster to start
  untrusted-postgresql-k8s/2 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] active: 
  untrusted-postgresql-k8s/1 [idle] waiting: awaiting for cluster to start
  untrusted-postgresql-k8s/2 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  untrusted-postgresql-k8s/0 [idle] active: 
  untrusted-postgresql-k8s/1 [idle] active: 
  untrusted-postgresql-k8s/2 [executing] active: Primary
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.4    unsupported  02:42:46Z

App                       Version  Status  Scale  Charm           Channel  Rev  Address         Exposed  Message
untrusted-postgresql-k8s  14.12    active      3  postgresql-k8s             0  10.152.183.185  no       

Unit                         Workload  Agent  Address     Ports  Message
untrusted-postgresql-k8s/0   active    idle   10.1.80.75         
untrusted-postgresql-k8s/1   active    idle   10.1.80.77         
untrusted-postgresql-k8s/2*  active    idle   10.1.80.76         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

model-cb2f6f80-1493-45fc-8eb9-9dd9ffeb0c20: 02:30:31 ERROR juju.kubernetes.klog /build/snapcraft-juju-c90e67be988b0e4d002ce9f34fba0b99/parts/jujud/build/worker/caasrbacmapper/mapper.go:79: Failed to watch *v1.ServiceAccount: unknown (get serviceaccounts) - error from a previous attempt: read tcp 10.1.80.71:45034->10.152.183.1:443: read: connection reset by peer
unit-untrusted-postgresql-k8s-2: 02:32:47 ERROR unit.untrusted-postgresql-k8s/2.juju-log 
            Access to k8s cluster resources is not authorized. This happens when RBAC is enabled and the deployed application was not trusted by the juju admin.
            To fix this issue, run `juju trust untrusted-postgresql-k8s --scope=cluster` (or remove & re-deploy untrusted-postgresql-k8s with `--trust`)
            
unit-untrusted-postgresql-k8s-2: 02:32:47 ERROR unit.untrusted-postgresql-k8s/2.juju-log 
            Access to k8s cluster resources is not authorized. This happens when RBAC is enabled and the deployed application was not trusted by the juju admin.
            To fix this issue, run `juju trust untrusted-postgresql-k8s --scope=cluster` (or remove & re-deploy untrusted-postgresql-k8s with `--trust`)
            

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...