{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"AssertionError: assert 0 == 1\n +  where 0 = <built-in function countOf>(dict_values(['primary', 'replica', 'replica']), 'master')\n +    where <built-in function countOf> = operator.countOf\n +    and   dict_values(['primary', 'replica', 'replica']) = <built-in method values of dict object at 0x796cb2b0d880>()\n +      where <built-in method values of dict object at 0x796cb2b0d880> = {'postgresql-k8s/0': 'primary', 'postgresql-k8s/1': 'replica', 'postgresql-k8s/2': 'replica'}.values","children":[{"name":"test_deploy_stable","uid":"fe8fce079f653f88","parentUid":"3c1c9b06d3c02d421c9afc8b04505911","status":"failed","time":{"start":1733796504054,"stop":1733796798199,"duration":294145},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["unstable","asyncio","abort_on_fail","@pytest.mark.skipif(False, reason='Requires amd64 architecture')","group(1)"]}],"uid":"3c1c9b06d3c02d421c9afc8b04505911"},{"name":"AssertionError: assert 0 == 1\n +  where 0 = <built-in function countOf>(dict_values(['replica', 'replica', 'primary']), 'master')\n +    where <built-in function countOf> = operator.countOf\n +    and   dict_values(['replica', 'replica', 'primary']) = <built-in method values of dict object at 0x7f8f85242200>()\n +      where <built-in method values of dict object at 0x7f8f85242200> = {'postgresql-k8s/0': 'replica', 'postgresql-k8s/1': 'replica', 'postgresql-k8s/2': 'primary'}.values","children":[{"name":"test_fail_and_rollback","uid":"f4d7de015166ef2d","parentUid":"7b17ce6e0d1135112303baf9ba581a10","status":"failed","time":{"start":1733797150257,"stop":1733797664852,"duration":514595},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["unstable","asyncio","@pytest.mark.skipif(False, reason='Requires amd64 architecture')","group(1)"]}],"uid":"7b17ce6e0d1135112303baf9ba581a10"},{"name":"AssertionError: Not all units down at the same time.\nassert False","children":[{"name":"test_full_cluster_restart[SIGTERM-/usr/bin/patroni]","uid":"3770fa8f37470b63","parentUid":"18d09cc6a4c986fbda58869f620aa058","status":"failed","time":{"start":1733798413867,"stop":1733798490408,"duration":76541},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":["'/usr/bin/patroni'","'SIGTERM'"],"tags":["unstable","asyncio","group(1)"]},{"name":"test_full_cluster_restart[SIGKILL-/usr/bin/patroni]","uid":"3aa6037d54adeb2e","parentUid":"18d09cc6a4c986fbda58869f620aa058","status":"failed","time":{"start":1733798749851,"stop":1733798831760,"duration":81909},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":["'/usr/bin/patroni'","'SIGKILL'"],"tags":["unstable","asyncio","group(1)"]}],"uid":"18d09cc6a4c986fbda58869f620aa058"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"},{"name":"Test defects","children":[{"name":"TypeError: change_patroni_setting() missing 1 required positional argument: 'password'","children":[{"name":"test_full_cluster_restart[SIGTERM-postgres]","uid":"776b1e05899db2f3","parentUid":"d3953d9f89aa1a7c672abd70877284c7","status":"broken","time":{"start":1733798241950,"stop":1733798286839,"duration":44889},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":["'postgres'","'SIGTERM'"],"tags":["unstable","asyncio","group(1)"]},{"name":"test_full_cluster_restart[SIGKILL-postgres]","uid":"83ea1a14d86fcdb0","parentUid":"d3953d9f89aa1a7c672abd70877284c7","status":"broken","time":{"start":1733798598153,"stop":1733798638161,"duration":40008},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":["'postgres'","'SIGKILL'"],"tags":["unstable","asyncio","group(1)"]}],"uid":"d3953d9f89aa1a7c672abd70877284c7"},{"name":"botocore.exceptions.NoCredentialsError: Unable to locate credentials","children":[{"name":"test_pitr_backup_aws","uid":"d1f93a261e836ca","parentUid":"1bcd49e6f105cc45c61e409e860609ba","status":"broken","time":{"start":1733798569655,"stop":1733799693620,"duration":1123965},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["asyncio","abort_on_fail","group(1)"]},{"name":"test_backup_aws","uid":"97b309365f0d7c6","parentUid":"1bcd49e6f105cc45c61e409e860609ba","status":"broken","time":{"start":1733799071861,"stop":1733800335261,"duration":1263400},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["asyncio","abort_on_fail","group(1)"]}],"uid":"1bcd49e6f105cc45c61e409e860609ba"},{"name":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\npostgresql-k8s-gcp/0 [idle] waiting: awaiting for cluster to start\n  postgresql-k8s-gcp/1 [idle] active: Primary","children":[{"name":"test_backup_gcp","uid":"ab618c6276e6c248","parentUid":"fc409ea7169d7dab75345abf88d47bf7","status":"broken","time":{"start":1733798611163,"stop":1733799642236,"duration":1031073},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["asyncio","abort_on_fail","group(2)"]}],"uid":"fc409ea7169d7dab75345abf88d47bf7"},{"name":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\ns3-integrator/0 [idle] blocked: Missing parameters: ['access-key', 'secret-key']","children":[{"name":"test_pitr_backup_gcp","uid":"ca101d687b95fc6c","parentUid":"c1942a31d86a4f92c2b89be2bb882f7e","status":"broken","time":{"start":1733798853372,"stop":1733800204973,"duration":1351601},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["asyncio","abort_on_fail","group(2)"]}],"uid":"c1942a31d86a4f92c2b89be2bb882f7e"},{"name":"subprocess.CalledProcessError: Command 'kubectl apply -f /tmp/tmpfwposcma' returned non-zero exit status 127.","children":[{"name":"test_network_cut","uid":"22c5eb8de833b133","parentUid":"46a51954a9e0c92e1a56f197d9d12931","status":"broken","time":{"start":1733798936193,"stop":1733799007568,"duration":71375},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["asyncio","@pytest.mark.skipif(False, reason='Requires amd64 architecture')","group(1)"]}],"uid":"46a51954a9e0c92e1a56f197d9d12931"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}